# action.yml
name: 'Huawei OBS Helper'
description: 'Upload/Download files or folders to Huawei OBS'
inputs:
  access_key:
    description: "Access key id"
    required: true
  secret_key:
    description: "Secret access key"
    required: true
  region:
    description: 'Region'
    required: false
    default: 'cn-north-4'
  bucket_name:
    description: "The name of the bucket you want to upload or download"
    required: true
  operation_type:
    description: upload or download
    required: true
  file_path:
    description: "The name of the file or directory you want to upload or download"
    required: true  
runs:
  using: 'docker'
  image: 'Dockerfile'
