# action.yml
name: 'HuaweiCloud OBS Helper'
description: 'Upload/Download files or folders to HuaweiCloud OBS'
inputs:
  access_key:
    description: "Access key id"
    required: true
  secret_key:
    description: "Secret access key"
    required: true
  region:
    description: 'Region'
    required: false
    default: 'cn-north-4'
  bucket_name:
    description: "The name of the bucket"
    required: true
  operation_type:
    description: "download or upload object, create or delete bucket"
    required: true
  local_file_path:
    description: "Local file/folder path"
    required: false
  obs_file_path:
    description: "The file/folder path of obs bucket"
    required: false  
  include_self_folder:
    description: "Include root folder when upload or download"
    required: false
  exclude:
    description: "Exclude file or folder when download a folder"
    required: false
  ACL:
    description: "Pre-defined access control policy that can be specified during the bucket creation"
    required: false
  storage_class:
    description: "Bucket storage class that can be specified during the bucket creation"
    required: false
  clear_bucket:
    description: "Whether to delete all objects and parts in the bucket"
    required: false
    default: true
branding:
  icon: 'cloud'
  color: 'red'
runs:
  using: 'node16'
  main: 'dist/index.js'
