# action.yml
name: 'HuaweiCloud OBS Helper'
description: 'Upload/Download files or folders to HuaweiCloud OBS'
inputs:
  access_key:
    description: "Access key id"
    required: true
  secret_key:
    description: "Secret access key"
    required: true
  region:
    description: 'Region'
    required: false
    default: 'cn-north-4'
  bucket_name:
    description: "The name of the bucket you want to upload or download"
    required: true
  operation_type:
    description: upload or download
    required: true
  local_file_path:
    description: "Local file/folder path"
    required: true
  obs_file_path:
    description: "The file/folder path of obs bucket"
    required: true  
  include_self_folder:
    description: "Include root folder when upload or download"
    required: false
  exclude:
    description: "Exclude file or folder when download a folder"
    required: false
branding:
  icon: 'cloud'
  color: 'red'
runs:
  using: 'node16'
  main: 'dist/index.js'
