on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # 使用华为云统一鉴权
      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.0.0
        with: 
          access_key_id: ${{ secrets.ACCESSKEY }} 
          secret_access_key: ${{ secrets.SECRETACCESSKEY }}
          region: cn-north-4
      # 创建桶
      - name: Create Bucket on Huawei Cloud OBS
        uses: ./
        id: create_bucket_on_obs
        with:
          bucket_name: new-bucket
          operation_type: createBucket
          public_read: true
      # 上传文件至桶
      - name: Upload To Huawei OBS
        uses: ./
        id: upload_file_to_obs
        with:
          bucket_name: new-bucket
          local_file_path: README.md
          obs_file_path: 
          operation_type: upload
      # 从桶内下载文件
      - name: Download from Huawei OBS
        uses: ./
        id: download_file_from_obs
        with:
          bucket_name: new-bucket
          local_file_path: ${{ github.workspace }}
          obs_file_path: test.txt
          operation_type: download
      # 删除桶
      - name: Delete Bucket on Huawei Cloud OBS
        uses: ./
        id: delete_bucket_on_obs
        with:
          bucket_name: new-bucket
          operation_type: deleteBucket